title: Max Slemaker # your name (or website title) here
logo: "/images/portfolio_picture(2).png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a web developer and designer based in the dallas area with a focus on UI/UX design.
  <br><br>
  Experienced with designing and developing Wordpress and other CMS platform sites.
  <br><br>
  <a href="https://www.linkedin.com/in/max-slemaker-244569191/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
